name: scdiff PR evaluation
on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  golden-test:
    if: ${{ (github.event.issue.pull_request) && (contains(github.event.comment.body, '/scdiff generate')) }}
    runs-on: [ubuntu-latest]
    steps:
      - name: repos to run anlaysis on
        run: |
          cat << EOF
          github.com/ossf/scorecard-action
          github.com/ossf/scorecard-webapp
          EOF > repos.txt
      - name: fetch base and head shas
        id: pr-refs
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PULL_NUMBER: ${{ github.event.issue.number }}
          REPOSITORY: ${{ github.repository }}
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$REPOSITORY/pulls/$PULL_NUMBER > pr.json
          echo "SCDIFF_BASE_SHA=$(jq -r '.base.sha' pr.json)" >> "$GITHUB_ENV"
          echo "SCDIFF_HEAD_SHA=$(jq -r '.head.sha' pr.json)" >> "$GITHUB_ENV"
      - run: |
          echo ${{ env.SCDIFF_BASE_SHA }}
          echo ${{ env.SCDIFF_HEAD_SHA }}
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          ref: ${{ env.SCDIFF_BASE_SHA }}
      - name: generate before results
        run: |
          go run cmd/internal/scdiff/main.go generate --repos repos > before.json
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          ref: ${{ env.SCDIFF_HEAD_SHA }}
      - name: generate after results
        run: |
          go run cmd/internal/scdiff/main.go generate --repos repos > after.json
      - name: compare results
        run: |
          go run cmd/internal/scdiff/main.go compare before.json after.json
